[package]
name = "lsh"
version = "0.2.4"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = true

[[example]]
# crate-type can't be (at the moment) be overriden for specific targets
# src/wasm_lib.rs forwards to src/lib.rs so that we can change from cdylib
# (that is needed while compiling natively) to staticlib (needed since the
# actual linking will be done via emcc
name = "lsh"
path = "src/wasm_lib.rs"
crate-type = ["staticlib"]

[dependencies]
duckdb = { version = "1.10501.0", features = ["vscalar", "vtab-arrow"] }
duckdb-loadable-macros = "1.10501.0"
libduckdb-sys = { version = "1.10501.0", features = ["loadable-extension"] }
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
nohash-hasher = "0.2.0"
rand = "0.8.5"
rustc-hash = "1.1.0"
